# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='Название')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('image', models.FileField(upload_to=landing.models.generate_filename)),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('the_type', models.CharField(choices=[('FRU', 'Фрукт'), ('NUT', 'Орех')], default='FRU', max_length=3)),
            ],
        ),
    ]
