# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='the_type',
            field=models.CharField(choices=[('FRU', 'Фрукт'), ('NUT', 'Орех')], default='FRU', max_length=3, verbose_name='Тип'),
        ),
    ]
