# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20160605_1435'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Заказы',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Продукты',
        ),
    ]
