# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20160605_1504'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
