# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20160605_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='Название типа')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to=landing.models.generate_filename, verbose_name='Картинка'),
        ),
    ]
