# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20160605_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nut_type',
            field=models.ManyToManyField(to='landing.NutType'),
        ),
    ]
