# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_product_nut_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nut_type',
            field=models.ManyToManyField(to='landing.NutType', verbose_name='Тип ореха'),
        ),
    ]
