# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20160605_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuttype',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Тип ореха'),
        ),
    ]
