# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 19:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20160605_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.TextField(blank=True, default='', verbose_name='Лист заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nut_type',
            field=models.ManyToManyField(to='landing.NutType', verbose_name='Тип ореха'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена(руб/кг)'),
        ),
    ]
