# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20160606_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nut_type',
            field=models.ManyToManyField(blank=True, null=True, to='landing.NutType', verbose_name='Тип ореха'),
        ),
    ]
